services:
  test-backend-5:
    build:
      context: .
      target: production
    image: test-backend-5
    container_name: test-backend-5
    depends_on:
      - test-backend-5-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: test-backend-5-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  test-backend-5-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: test-backend-5
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
